### ISSUE TITLE
Help with imports

### ISSUE THREAD

**Issue by igillis** [mysterlune/ember-cli-list-view#1]
Hey @mysterlune, thanks for doing this! I've installed ember-cli-list-view with 

`npm install ember-cli-list-view --save-dev && ember generate ember-cli-list-view`

but when I do something like
`import ListItemView from 'list-view/list_item_view'`
the import fails. Any ideas? It looks like your blueprint does all of the app.import stuff so I don't think that's the issue.

I'm fairly new to ES6/ember-cli stuff so I'm sure there's something stupid I'm missing -- thanks for any help!

**Comment by mysterlune** [comment]
if you are using an ember-cli project, you can do:

app.import('bower_components/ember-cli-list-view/list-view.js');

... in your Brocfile.js.

let me know if that helps, or if something else is wrong.

**Comment by mysterlune** [comment]
Also, just as an FYI, the current codebase in use here for ListView is from the `pack` branch of emberjs/list-view, and not master.

I'm trying to get my process down for maintaining this shim, but at the same time wanting features that aren't in master yet... So, naturally, I'm learning my lesson as I also now cannot get past some JS errors regarding undefined values, etc.

It probably makes sense to shim the master branch, so I'll push in a change shortly.

**Comment by igillis** [comment]
Wasn't able to get it to work. I'm trying to use it as a dependency for an addon, so perhaps that has something to do with it? 

Not a huge deal -- I can just use the vendor/list-view installation from the original project for now.

**Comment by mysterlune** [comment]
no worries. i'm in the process of converting this to an addon now, so it should hopefully work out of the box soon. also, it'll help when i've got a build using the master branch here ;)
