### ISSUE TITLE
ember-list-view is now live

### ISSUE THREAD

**Issue by taras** [mysterlune/ember-cli-list-view#4]
Thank you for creating this addon. I'm sure it was useful to people when ListView was not an Ember addon. We just release `ember-list-view` on NPM. It's now possible to add list view to the project by installing `ember-list-view` addon. 

To prevent confusion, could you please reference `ember-list-view` in your README?

**Comment by mysterlune** [comment]
Yes. Thanks for the reminder. I'll put in the deprecation notice...

**Comment by mysterlune** [comment]
@taras Done. Added deprecation update to this package and the bower shim (ember-list-veiw-component). Also, unregistered the Bower package so folks don't accidentally get that installed when they find old notes on Github or Stackoverflow.

Great work on the addon, btw. Thanks for making it happen.

**Comment by joebartels** [comment]
Just a note that this will break builds and some folks may not be able to easily upgrade to use `ember-list-view` (the addon). e.g., if they're using [ember-widgets](https://github.com/addepar/ember-widgets) which currently relies on the global definition of `Ember.ListView` that's provided using the [shim, here](https://github.com/geekingreen/ember-list-view)

a workaround until everything is smoothed out:
`bower install ember-list-view`
`npm install joebartels/ember-cli-list-view#work_with_bower`

**Comment by mysterlune** [comment]
Thanks, @joebartels. You're right about breaking folks' builds.

Your shim is definitely a good way for users to maintain compatibility.
